#!/usr/bin/with-contenv bash

### Set Defaults
DB_TYPE=${DB_TYPE:-"mysql"}
DB_HOST=${DB_HOST:-"orbeon-db"}
DB_PORT=${DB_PORT:-"3306"}

DB_NAME=${DB_NAME:-"orbeon"}
DB_USER=${DB_USER:-"orbeon"}
DB_PASS=${DB_PASS:-"password"}
ORBEON_ROOT=${ORBON_ROOT:-"/"}

### Set Database
if [ "$DB_TYPE" = "mysql" ] || [ "$DB_TYPE" = "mariadb" ];  then

    while true; do
      mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
      out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
      echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
      if [ $? -eq 0 ]; then
        echo "** [orbeon] MySQL Database Connection Established"
        break
      fi
      echo "** [orbeon] MySQL Database Connection Not avilable, retrying.."
      sleep 2
    done

    cat <<EOF > /tmp/mariadb  
    <Resource 
        name="jdbc/mysql"
        driverClassName="org.mariadb.jdbc.Driver"

        auth="Container" 
        type="javax.sql.DataSource"

        initialSize="3" 
        maxTotal="10" 
        maxIdle="10" 
        maxWaitMillis="30000"

        poolPreparedStatements="true"

        testOnBorrow="true"
        validationQuery="select 1"

        username="$DB_USER"
        password="$DB_PASS"
        url="jdbc:mysql://$DB_HOST:$DB_PORT/$DB_NAME?useUnicode=true&amp;characterEncoding=UTF8"/>
EOF

    cat <<EOF> /tmp/mariadb.sql
ALTER DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS orbeon_form_definition (
    created             TIMESTAMP(6)                                                              ,
    last_modified_time  TIMESTAMP(6)                                                              ,
    last_modified_by    VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    app                 VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form                VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form_version        INT                                                               NOT NULL,
    form_metadata       VARCHAR(4000)                             COLLATE utf8_bin                ,
    deleted             CHAR(1)                                   COLLATE utf8_bin        NOT NULL,
    xml                 MEDIUMTEXT             CHARACTER SET utf8 COLLATE utf8_unicode_ci
)   ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS orbeon_form_definition_attach (
    created             TIMESTAMP(6)                                                              ,
    last_modified_time  TIMESTAMP(6)                                                              ,
    last_modified_by    VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    app                 VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form                VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form_version        INT                                                               NOT NULL,
    deleted             CHAR(1)                                   COLLATE utf8_bin        NOT NULL,
    file_name           VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    file_content        LONGBLOB
)   ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS orbeon_form_data (
    id                  INT                    PRIMARY KEY AUTO_INCREMENT                 NOT NULL,
    created             TIMESTAMP(6)                                                              ,
    last_modified_time  TIMESTAMP(6)                                                              ,
    last_modified_by    VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    username            VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    groupname           VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    organization_id     INT                                                                       ,
    app                 VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form                VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form_version        INT                                                               NOT NULL,
    document_id         VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    draft               CHAR(1)                                   COLLATE utf8_bin        NOT NULL,
    deleted             CHAR(1)                                   COLLATE utf8_bin        NOT NULL,
    xml                 MEDIUMTEXT             CHARACTER SET utf8 COLLATE utf8_unicode_ci
)   ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS orbeon_form_data_attach (
    created             TIMESTAMP(6)                                                              ,
    last_modified_time  TIMESTAMP(6)                                                              ,
    last_modified_by    VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    username            VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    groupname           VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    organization_id     INT                                                                       ,
    app                 VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form                VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    form_version        INT                                                               NOT NULL,
    document_id         VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    draft               CHAR(1)                                   COLLATE utf8_bin        NOT NULL,
    deleted             CHAR(1)                                   COLLATE utf8_bin        NOT NULL,
    file_name           VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin                ,
    file_content        LONGBLOB
)   ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS orbeon_organization (
    id                  INT                                                               NOT NULL,
    depth               INT                                                               NOT NULL,
    pos                 INT                                                               NOT NULL,
    name                VARCHAR(255)           CHARACTER SET utf8 COLLATE utf8_bin        NOT NULL
)   ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS orbeon_seq (
    val                 INT                    PRIMARY KEY AUTO_INCREMENT                 NOT NULL
)   ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS orbeon_i_current (
    data_id             INT                                                               NOT NULL,
    created             TIMESTAMP(6)                                                      NOT NULL,
    last_modified_time  TIMESTAMP(6)                                                      NOT NULL,
    last_modified_by    VARCHAR(255)          CHARACTER SET utf8 COLLATE utf8_bin                 ,
    username            VARCHAR(255)          CHARACTER SET utf8 COLLATE utf8_bin                 ,
    groupname           VARCHAR(255)          CHARACTER SET utf8 COLLATE utf8_bin                 ,
    organization_id     INT                                                                       ,
    app                 VARCHAR(255)          CHARACTER SET utf8 COLLATE utf8_bin         NOT NULL,
    form                VARCHAR(255)          CHARACTER SET utf8 COLLATE utf8_bin         NOT NULL,
    form_version        INT                                                               NOT NULL,
    document_id         VARCHAR(255)          CHARACTER SET utf8 COLLATE utf8_bin         NOT NULL,
    draft               CHAR(1)                                                           NOT NULL,
    FOREIGN KEY         (data_id)             REFERENCES orbeon_form_data(id)
)   ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS orbeon_i_control_text (
    data_id             INT                                                               NOT NULL,
    pos                 INT                                                               NOT NULL,
    control             VARCHAR(255)          CHARACTER SET utf8 COLLATE utf8_bin         NOT NULL,
    val                 MEDIUMTEXT            CHARACTER SET utf8 COLLATE utf8_unicode_ci  NOT NULL,
    FOREIGN KEY         (data_id)             REFERENCES orbeon_form_data(id)
)   ENGINE = InnoDB;
EOF

    cat <<EOF> /usr/local/tomcat/webapps/orbeon/WEB-INF/resources/config/properties-prod.xml
<properties xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:oxf="http://www.orbeon.com/oxf/processors">

<property
  as="xs:anyURI"
  name="oxf.fr.persistence.app.uri.*.*.data"
  value="/fr/service/mysql"/>

</properties>
EOF

    mysql -u$DB_USER -h$DB_HOST -p$DB_PASS $DB_NAME</tmp/mariadb.sql
    sed -i '/pathname="conf\/tomcat-users.xml" \/>/ r /tmp/mariadb' /usr/local/tomcat/conf/server.xml
    rm -rf /tmp/mariadb*
    echo '** [orbeon] Database Configured to '$DB_HOST'/'$DB_NAME
fi

### Set Root
    mkdir -p /data/
    if [ ! -d "/data/fs" ]; then
        cp -R /usr/local/tomcat/webapps/orbeon/WEB-INF/exist-data/* /data/
    fi
        rm -rf /usr/local/tomcat/webapps/orbeon/WEB-INF/exist-data
        ln -s /data /usr/local/tomcat/webapps/orbeon/WEB-INF/exist-data

    if [ "$ORBEON_ROOT" = "/" ];  then
        mv /usr/local/tomcat/webapps/ROOT /usr/local/tomcat/webapps/ROOTx
        rm -rf /usr/local/tomcat/webapps/ROOTx
        mv /usr/local/tomcat/webapps/orbeon /usr/local/tomcat/webapps/ROOT
    else
        mv /usr/local/tomcat/webapps/orbeon /usr/local/tomcat/webapps/$ORBEON_ROOT
    fi


mkdir -p /tmp/state
touch /tmp/state/11-orbeon-init